on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        run:  |
              ./build.sh
      - name: Activate
        run:  |
              . venv/bin/activate
      - name: Lint
        run:  |   
              lint.sh
      - name: Test
        run:  |
              test.sh
