on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.7"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run:  |
              ./build.sh
      - name: Activate
        run:  |
              . venv/bin/activate
      - name: Lint
        run:  |   
              lint.sh
      - name: Test
        run:  |
              test.sh
