on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Build
        run:  |
              ./build.sh
      - name: Activate
        run:  |
              . venv/bin/activate
      - name: Lint
        run:  |   
              ./lint.sh
      - name: Test
        run:  |
              ./test.sh
